---
name: Go

on:
  push:
  pull_request:
    types: [opened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yq  # Install yq for parsing YAML files

  # taskcli section
    - name: Run tests taskcli
      run: |
        make -C taskcli test 

    - name: Build taskcli
      run: |
        make -C taskcli build 

  # taskmgr section
    - name: Run tests taskmgr
      run: |
        make -C taskmgr test 

    - name: Build taskmgr
      run: |
        make -C taskmgr build 