name: E2E Tests

on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations
        env:
          GOOSE_DRIVER=postgres
          GOOSE_DBSTRING=postgres://test:test@postgres:5432/testdb
          GOOSE_MIGRATION_DIR=./taskmgr/goose
        run: goose up

      - name: Load test data into PostgreSQL
        run: |
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB -f e2e/setup.sql

      - name:
        run: |
          psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT * FROM task;"
          psql -h localhost -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT * FROM author;"

