---
name: Lint Go Code

on:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - name: Install Dependencies for CGo (Linux)
        run: sudo apt-get update && sudo apt-get install -y xorg-dev libgl1-mesa-dev

      - name: Install dependencies
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v.1.64.8

      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yml
